// Harness for mono-site tests: builds a minimal, monolingual, hook-free
// Hugo site against the *local* theme — offline and fast, in contrast with the
// smoke tests, which fetch Docsy from GitHub. Each test seeds its own targeted
// site content under the repo root's tmp/mono-site/, builds it, and asserts
// over the rendered output. See https://github.com/google/docsy/issues/726.

import { spawnSync } from 'node:child_process';
import {
  cpSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../..',
);
const MONO_SITE_TMP = path.join(repoRoot, 'tmp', 'mono-site');

const baseConfig = (name) => `# Generated by tests/mono-site/lib/build-site.mjs
title: Docsy mono-site fixture — ${name}
baseURL: https://example.org/
theme: theme
themesDir: ${repoRoot}
`;

// Build a mono-site fixture named `name` under tmp/mono-site/ (repo root).
// Site files come from `srcDir` (a checked-in fixture directory), `files`
// (a relative-path → content map), or both. The generated hugo.yaml can be
// extended via `extraConfig`. Returns the spawnSync result plus the site
// path and a `publicFile(relPath)` reader over the build output.
export function buildSite(name, { files = {}, srcDir, extraConfig = '' } = {}) {
  const site = path.join(MONO_SITE_TMP, name);
  rmSync(site, { recursive: true, force: true });
  mkdirSync(site, { recursive: true });
  if (srcDir) cpSync(srcDir, site, { recursive: true });
  writeFileSync(path.join(site, 'hugo.yaml'), baseConfig(name) + extraConfig);
  for (const [rel, content] of Object.entries(files)) {
    const f = path.join(site, rel);
    mkdirSync(path.dirname(f), { recursive: true });
    writeFileSync(f, content);
  }
  // PostCSS & friends, resolved from the repo's own install.
  symlinkSync(
    path.join(repoRoot, 'node_modules'),
    path.join(site, 'node_modules'),
  );
  const r = spawnSync('npx', ['hugo'], { cwd: site, encoding: 'utf8' });
  return {
    ...r,
    site,
    publicFile: (rel) => readFileSync(path.join(site, 'public', rel), 'utf8'),
  };
}
