# cSpell:ignore docsy github lookandfeel iconsimages

globs:
  - '!node_modules/**'
  - '!public/**'
  - '!tmp/**'
  - '!docsy.dev/**'
  - docsy.dev/content/en/docs/content/iconsimages.md
  - docsy.dev/content/en/docs/content/language.md
  - docsy.dev/content/en/docs/content/lookandfeel.md
  - docsy.dev/content/en/docs/content/navigation.md
  # - docsy.dev/content/en/docs/content/repository-links.md
  # - docsy.dev/content/en/docs/content/search.md
  # - docsy.dev/content/en/docs/content/shortcodes.md
  # - docsy.dev/content/en/docs/content/versioning.md
config:
  extends: .markdownlint.yaml
