# cSpell:ignore docsy github lookandfeel iconsimages

globs:
  - '!docsy.dev/**'
  - '!layouts/**'
  - '!node_modules/**'
  - '!public/**'
  - '!tmp/**'
  - 'docsy.dev/content/en/blog/**/*.md'
  - 'docsy.dev/content/en/docs/_index.md'
  - 'docsy.dev/content/en/docs/content/**/*.md'
  - 'docsy.dev/content/en/docs/best-practices/**/*.md'
  - 'docsy.dev/content/en/docs/get-started/other-options.md'
  - 'docsy.dev/content/en/docs/language.md'
  - 'docsy.dev/content/en/site/**/*.md'

config:
  extends: .markdownlint.yaml
