# See https://github.com/DavidAnson/markdownlint/blob/main/README.md#rules--aliases
# cSpell:ignore docsy

default: true

blanks-around-fences: false
emphasis-style: false
first-line-h1: false
line-length: false
link-fragments: false
list-marker-space: false
no-emphasis-as-header: false
no-hard-tabs: false
no-inline-html: false
no-trailing-punctuation: false
no-trailing-spaces: {  br_spaces: 0, strict: true}
# table-column-style: false

# Link-validation rules (from scripts/_md-rules/link-rules.mjs)

no-docsy-dev-external-urls:
  pattern: 'https?://(?:www\.)?docsy\.dev/'
  message: Use a site-relative path instead of the full docsy.dev URL.
  replace: '/'
