#!/usr/bin/env perl
#
# Generate config/doc-rooted/module.yaml from the mounts section in
# config/_default/hugo.yaml. Commented lines with "# for doc-rooted: uncomment"
# (case insensitive) are enabled (uncommented) in the output. Other commands
# may be added later.
#
# Usage: perl scripts/gen-doc-rooted-module.pl
# Run from the docsy.dev directory.

use strict;
use warnings;

# Return lines from $lines starting at a line matching $marker (regex) until the
# end of that section (next line at same or lesser indent) or end of array.
sub get_section {
    my ($lines, $marker) = @_;
    my @out;
    my $marker_indent = -1;

    for my $line (@$lines) {
        if ($marker_indent < 0) {
            next unless $line =~ $marker;
            $marker_indent = $line =~ m/^(\s*)/ ? length($1) : 0;
            push @out, $line;
            next;
        }
        my $indent = $line =~ m/^(\s*)/ ? length($1) : 0;
        last if $line =~ m/\S/ && $indent <= $marker_indent;
        push @out, $line;
    }
    return @out;
}

# Remove $n leading spaces from each line (only when the line has at least $n).
sub unindent {
    my ($lines, $n) = @_;
    return map { /^\s{$n,}/ ? substr($_, $n) : $_ } @$lines;
}

# Apply "for doc-rooted: <command>" directives. For "uncomment", drop the leading
# "# " and leave the directive in place. Other commands may be added later.
sub apply_directives {
    my ($lines) = @_;
    my @out;
    for my $line (@$lines) {
        if ($line =~ m/^(\s*)#\s+(.+?)(\s+#\s*for\s+doc-rooted:\s*uncomment\s*)$/i) {
            push @out, $1 . $2 . $3;
        } else {
            push @out, $line;
        }
    }
    return @out;
}

my $config_default = 'config/_default/hugo.yaml';
my $config_out     = 'config/doc-rooted/module.yaml';

open my $in, '<', $config_default or die "Cannot read $config_default: $!";
my @lines = <$in>;
close $in;

my @section = get_section(\@lines, qr/^\s*mounts:\s*$/);
die "Could not find 'mounts:' section in $config_default\n" unless @section;

@section = unindent(\@section, 2);
@section = apply_directives(\@section);

my $header = <<'HEADER';
# DO NOT EDIT. Generated by scripts/gen-doc-rooted-module.pl from
# config/_default/hugo.yaml (module.mounts).

HEADER

open my $out, '>', $config_out or die "Cannot write $config_out: $!";
print $out $header, @section;
close $out;

print "Wrote $config_out\n";
