blank_issues_enabled: false
contact_links:
  - name: SUPPORT, ISSUES, and TROUBLESHOOTING
    url: https://github.com/google/docsy/discussions
    about:
      Please DO NOT use GitHub issues for support requests, instead start a
      discussion thread at https://github.com/google/docsy/discussions. Feel
      free to open an issue once your problem is confirmed by the docsy
      maintainers and/or the docsy community.
