# cSpell:ignore pagelinks
#
# Version related parameters
#
# archived_version: false # TODO: generalize status
# version:
#   status: archived # Then fetch include

tdVersion:
  latest: &tdLatestVers v0.15.0
  dev: &tdDevVers v0.15.1-dev
  buildId: &tdBuildId 002-over-main-ce9942b8

version: *tdDevVers
version_menu: *tdDevVers
version_menu_pagelinks: true
versions:
  - name: '**Versions**'
  - version: *tdDevVers
    # kind: next
    pagelinks: true
    url: https://main--docsydocs.netlify.app # TODO: use next.docsy.dev once available
  - version: *tdLatestVers
    kind: latest
    url: https://www.docsy.dev
  - name: ---
  - name: '**Variant**'
  - name: Doc-rooted (experimental)
    kind: home
    pagelinks: false # TODO: drop this once /docs/* redirects are implemented
    url: https://doc-rooted--docsydocs.netlify.app
